### ISSUE TITLE
Build - Error: Cannot find module 'webfontloader'

### ISSUE THREAD

**Issue by hepiyellow** [lsu-emdm/nexusUI#66]
Getting this error (with latest clone from git), maybe `webfontloader` is missing from package.json dependencies? 
```
Erezs-MacBook-Pro:nexusUI hepi$ ./node_modules/gulp/bin/gulp.js 
[20:32:11] Using gulpfile ~/Documents/dev/nexusUI/gulpfile.js
[20:32:11] Starting 'default'...
[20:32:11] Starting 'browserify'...
[20:32:12] { Error: Cannot find module 'webfontloader' from '/Users/hepi/Documents/dev/nexusUI'
    at /Users/hepi/Documents/dev/nexusUI/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/Users/hepi/Documents/dev/nexusUI/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/Users/hepi/Documents/dev/nexusUI/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/Users/hepi/Documents/dev/nexusUI/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/hepi/Documents/dev/nexusUI/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /Users/hepi/Documents/dev/nexusUI/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:123:15)
  stream: 
```

**Comment by turbo5** [comment]
Having the same problem. Any solutions u found perhaps?

**Comment by taylorbf** [comment]
Added webfontloader to package.json in commit 8d859fb . Sorry about that.

**Comment by turbo5** [comment]
Still not present in the npm repo
